services:
  laravel:
    container_name: laravel
    image: iut:latest
    networks:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html
  
  redis:
    container_name: redis
    image: redis:7.2.5
    networks: 
      - laravel
    volumes:
      - ./.docker/stores/redis:/data

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.19.1
    networks:
      - laravel
    ports:
      - 8025:8025

networks:
  laravel:
    driver: bridge